import type { Metadata } from "next";
import "./globals.css";
import { Inter } from 'next/font/google'
// import { Montserrat } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: "Kingo's Home Page",
  description: "Generated by Kingo dev",
};

export default function RootLayout({children,}: {children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <h2></h2>
        {children}</body>
    </html>
  )
}
